apiVersion: apps/v1
kind: Deployment
metadata:
  name: identities-db
  namespace: postgres
spec:
  replicas: 3
  selector:
    matchLabels:
      app: identities-db
  template:
    metadata:
      labels:
        app: identities-db
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccountName: identities-dba
      containers:
      - name: identities-db
        image: database
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: indentitiesdb-credentials
        volumeMounts:
        - mountPath: /var/lib/postgres/data
          name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: identitiesdb-claim