apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: postgresdb
        image: database
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgresdb-credentials
        volumeMounts:
        - mountPath: /var/lib/postgres/data
          name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: postgresdb-claim