apiVersion: v1
kind: Service
metadata:
  name: identities-database
  namespace: postgres
  labels:
    app: identities-database
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: identities-database