apiVersion: v1
kind: Service
metadata:
  name: postgresdb
  namespace: postgres
  labels:
    app: postgresdb
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgresdb