apiVersion: v1
kind: Service
metadata:
  name: identities-db
  namespace: postgres
  labels:
    app: identities-db
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: identities-db