apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: identities-db
  namespace: postgres
spec:
  hosts:
  - identities-db
  http:
    - route:
      - destination:
          host: identities-db
          port:
            number: 5432