apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dakasa
spec:
  hosts:
  - "*"
  gateways:
  - dakasa-gateway
  http:
  - match:
    - uri:
        exact: /api/login
    - uri:
        exact: /api/register
    route:
    - destination:
        host: identities
        port:
          number: 9080