apiVersion: apps/v1
kind: Deployment
metadata:
  name: identities
  labels:
    app: identities
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identities
  template:
    metadata:
      labels:
        app: identities
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccountName: identities
      containers:
      - name: identities
        image: identities:0.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        envFrom:
        - configMapRef:
            name: identities-credentials