apiVersion: v1
kind: Service
metadata:
  name: identitities
  labels:
    app: identities
    service: identities
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: identities
---
apiVersion: v1
kind: Service
metadata:
  name: postgresdb
  labels:
    app: postgresdb
spec:
  ports:
    # The port number to expose the service
    - port: 5432
  # Pod to route service traffic  
  selector:
    app: postgresdb