// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Identities microsservice
//
//	Microsservice API responsible about all identities core data
//	Schemes:
//	  http
//	  https
//	Host: identities.dakasa.com
//	BasePath: /v1
//	Version: 0.1.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
