// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostLoginOKCode is the HTTP code returned for type PostLoginOK
const PostLoginOKCode int = 200

/*
PostLoginOK Logged in with success

swagger:response postLoginOK
*/
type PostLoginOK struct {
	/*Token to grant access to user in restrict services

	 */
	XJWT string `json:"X-JWT"`
}

// NewPostLoginOK creates PostLoginOK with default headers values
func NewPostLoginOK() *PostLoginOK {

	return &PostLoginOK{}
}

// WithXJWT adds the xJWT to the post login o k response
func (o *PostLoginOK) WithXJWT(xJWT string) *PostLoginOK {
	o.XJWT = xJWT
	return o
}

// SetXJWT sets the xJWT to the post login o k response
func (o *PostLoginOK) SetXJWT(xJWT string) {
	o.XJWT = xJWT
}

// WriteResponse to the client
func (o *PostLoginOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-JWT

	xJWT := o.XJWT
	if xJWT != "" {
		rw.Header().Set("X-JWT", xJWT)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostLoginBadRequestCode is the HTTP code returned for type PostLoginBadRequest
const PostLoginBadRequestCode int = 400

/*
PostLoginBadRequest requested body reaches malformed

swagger:response postLoginBadRequest
*/
type PostLoginBadRequest struct {
}

// NewPostLoginBadRequest creates PostLoginBadRequest with default headers values
func NewPostLoginBadRequest() *PostLoginBadRequest {

	return &PostLoginBadRequest{}
}

// WriteResponse to the client
func (o *PostLoginBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostLoginForbiddenCode is the HTTP code returned for type PostLoginForbidden
const PostLoginForbiddenCode int = 403

/*
PostLoginForbidden users credential are incorrect

swagger:response postLoginForbidden
*/
type PostLoginForbidden struct {
}

// NewPostLoginForbidden creates PostLoginForbidden with default headers values
func NewPostLoginForbidden() *PostLoginForbidden {

	return &PostLoginForbidden{}
}

// WriteResponse to the client
func (o *PostLoginForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// PostLoginInternalServerErrorCode is the HTTP code returned for type PostLoginInternalServerError
const PostLoginInternalServerErrorCode int = 500

/*
PostLoginInternalServerError Occurs unexpected internal error

swagger:response postLoginInternalServerError
*/
type PostLoginInternalServerError struct {
}

// NewPostLoginInternalServerError creates PostLoginInternalServerError with default headers values
func NewPostLoginInternalServerError() *PostLoginInternalServerError {

	return &PostLoginInternalServerError{}
}

// WriteResponse to the client
func (o *PostLoginInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
