// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostRecoveryCreatedCode is the HTTP code returned for type PostRecoveryCreated
const PostRecoveryCreatedCode int = 201

/*
PostRecoveryCreated Created ticket recovery with success

swagger:response postRecoveryCreated
*/
type PostRecoveryCreated struct {

	/*
	  In: Body
	*/
	Payload *PostRecoveryCreatedBody `json:"body,omitempty"`
}

// NewPostRecoveryCreated creates PostRecoveryCreated with default headers values
func NewPostRecoveryCreated() *PostRecoveryCreated {

	return &PostRecoveryCreated{}
}

// WithPayload adds the payload to the post recovery created response
func (o *PostRecoveryCreated) WithPayload(payload *PostRecoveryCreatedBody) *PostRecoveryCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post recovery created response
func (o *PostRecoveryCreated) SetPayload(payload *PostRecoveryCreatedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostRecoveryCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostRecoveryBadRequestCode is the HTTP code returned for type PostRecoveryBadRequest
const PostRecoveryBadRequestCode int = 400

/*
PostRecoveryBadRequest requested body reaches malformed

swagger:response postRecoveryBadRequest
*/
type PostRecoveryBadRequest struct {
}

// NewPostRecoveryBadRequest creates PostRecoveryBadRequest with default headers values
func NewPostRecoveryBadRequest() *PostRecoveryBadRequest {

	return &PostRecoveryBadRequest{}
}

// WriteResponse to the client
func (o *PostRecoveryBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostRecoveryNotFoundCode is the HTTP code returned for type PostRecoveryNotFound
const PostRecoveryNotFoundCode int = 404

/*
PostRecoveryNotFound user not found

swagger:response postRecoveryNotFound
*/
type PostRecoveryNotFound struct {
}

// NewPostRecoveryNotFound creates PostRecoveryNotFound with default headers values
func NewPostRecoveryNotFound() *PostRecoveryNotFound {

	return &PostRecoveryNotFound{}
}

// WriteResponse to the client
func (o *PostRecoveryNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// PostRecoveryInternalServerErrorCode is the HTTP code returned for type PostRecoveryInternalServerError
const PostRecoveryInternalServerErrorCode int = 500

/*
PostRecoveryInternalServerError Occurs unexpected internal error

swagger:response postRecoveryInternalServerError
*/
type PostRecoveryInternalServerError struct {
}

// NewPostRecoveryInternalServerError creates PostRecoveryInternalServerError with default headers values
func NewPostRecoveryInternalServerError() *PostRecoveryInternalServerError {

	return &PostRecoveryInternalServerError{}
}

// WriteResponse to the client
func (o *PostRecoveryInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

// PostRecoveryServiceUnavailableCode is the HTTP code returned for type PostRecoveryServiceUnavailable
const PostRecoveryServiceUnavailableCode int = 503

/*
PostRecoveryServiceUnavailable Email service is unavailable and fails in sent recovery message.

swagger:response postRecoveryServiceUnavailable
*/
type PostRecoveryServiceUnavailable struct {
}

// NewPostRecoveryServiceUnavailable creates PostRecoveryServiceUnavailable with default headers values
func NewPostRecoveryServiceUnavailable() *PostRecoveryServiceUnavailable {

	return &PostRecoveryServiceUnavailable{}
}

// WriteResponse to the client
func (o *PostRecoveryServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(503)
}
