// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostChallRecoveryMaxParseMemory sets the maximum size in bytes for
// the multipart form parser for this operation.
//
// The default value is 32 MB.
// The multipart parser stores up to this + 10MB.
var PostChallRecoveryMaxParseMemory int64 = 32 << 20

// NewPostChallRecoveryParams creates a new PostChallRecoveryParams object
//
// There are no default values defined in the spec.
func NewPostChallRecoveryParams() PostChallRecoveryParams {

	return PostChallRecoveryParams{}
}

// PostChallRecoveryParams contains all the bound params for the post chall recovery operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostChallRecovery
type PostChallRecoveryParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*New account password
	  Required: true
	  In: formData
	*/
	Password string
	/*The ticket identity field
	  Required: true
	  In: formData
	*/
	Ticket string
	/*A random validation integer. The number get's a range between 100000 ~ 999999
	  Required: true
	  In: formData
	*/
	Validation int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostChallRecoveryParams() beforehand.
func (o *PostChallRecoveryParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := r.ParseMultipartForm(PostChallRecoveryMaxParseMemory); err != nil {
		if err != http.ErrNotMultipart {
			return errors.New(400, "%v", err)
		} else if err := r.ParseForm(); err != nil {
			return errors.New(400, "%v", err)
		}
	}
	fds := runtime.Values(r.Form)

	fdPassword, fdhkPassword, _ := fds.GetOK("password")
	if err := o.bindPassword(fdPassword, fdhkPassword, route.Formats); err != nil {
		res = append(res, err)
	}

	fdTicket, fdhkTicket, _ := fds.GetOK("ticket")
	if err := o.bindTicket(fdTicket, fdhkTicket, route.Formats); err != nil {
		res = append(res, err)
	}

	fdValidation, fdhkValidation, _ := fds.GetOK("validation")
	if err := o.bindValidation(fdValidation, fdhkValidation, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindPassword binds and validates parameter Password from formData.
func (o *PostChallRecoveryParams) bindPassword(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("password", "formData", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("password", "formData", raw); err != nil {
		return err
	}
	o.Password = raw

	return nil
}

// bindTicket binds and validates parameter Ticket from formData.
func (o *PostChallRecoveryParams) bindTicket(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("ticket", "formData", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("ticket", "formData", raw); err != nil {
		return err
	}
	o.Ticket = raw

	return nil
}

// bindValidation binds and validates parameter Validation from formData.
func (o *PostChallRecoveryParams) bindValidation(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("validation", "formData", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("validation", "formData", raw); err != nil {
		return err
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("validation", "formData", "int64", raw)
	}
	o.Validation = value

	return nil
}
