// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostRegisterHandlerFunc turns a function with the right signature into a post register handler
type PostRegisterHandlerFunc func(PostRegisterParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostRegisterHandlerFunc) Handle(params PostRegisterParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostRegisterHandler interface for that can handle valid post register params
type PostRegisterHandler interface {
	Handle(PostRegisterParams, interface{}) middleware.Responder
}

// NewPostRegister creates a new http.Handler for the post register operation
func NewPostRegister(ctx *middleware.Context, handler PostRegisterHandler) *PostRegister {
	return &PostRegister{Context: ctx, Handler: handler}
}

/*
	PostRegister swagger:route POST /register postRegister

Sign up user in service
*/
type PostRegister struct {
	Context *middleware.Context
	Handler PostRegisterHandler
}

func (o *PostRegister) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostRegisterParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
