// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostRegisterCreatedCode is the HTTP code returned for type PostRegisterCreated
const PostRegisterCreatedCode int = 201

/*
PostRegisterCreated Created user with success

swagger:response postRegisterCreated
*/
type PostRegisterCreated struct {
}

// NewPostRegisterCreated creates PostRegisterCreated with default headers values
func NewPostRegisterCreated() *PostRegisterCreated {

	return &PostRegisterCreated{}
}

// WriteResponse to the client
func (o *PostRegisterCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostRegisterBadRequestCode is the HTTP code returned for type PostRegisterBadRequest
const PostRegisterBadRequestCode int = 400

/*
PostRegisterBadRequest The user sent some bad data in form

swagger:response postRegisterBadRequest
*/
type PostRegisterBadRequest struct {
}

// NewPostRegisterBadRequest creates PostRegisterBadRequest with default headers values
func NewPostRegisterBadRequest() *PostRegisterBadRequest {

	return &PostRegisterBadRequest{}
}

// WriteResponse to the client
func (o *PostRegisterBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostRegisterConflictCode is the HTTP code returned for type PostRegisterConflict
const PostRegisterConflictCode int = 409

/*
PostRegisterConflict users with respective email, username or phone number already exists

swagger:response postRegisterConflict
*/
type PostRegisterConflict struct {
}

// NewPostRegisterConflict creates PostRegisterConflict with default headers values
func NewPostRegisterConflict() *PostRegisterConflict {

	return &PostRegisterConflict{}
}

// WriteResponse to the client
func (o *PostRegisterConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// PostRegisterInternalServerErrorCode is the HTTP code returned for type PostRegisterInternalServerError
const PostRegisterInternalServerErrorCode int = 500

/*
PostRegisterInternalServerError Unexpected error occurs in internal server

swagger:response postRegisterInternalServerError
*/
type PostRegisterInternalServerError struct {
}

// NewPostRegisterInternalServerError creates PostRegisterInternalServerError with default headers values
func NewPostRegisterInternalServerError() *PostRegisterInternalServerError {

	return &PostRegisterInternalServerError{}
}

// WriteResponse to the client
func (o *PostRegisterInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
