// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostChallRecoveryNoContentCode is the HTTP code returned for type PostChallRecoveryNoContent
const PostChallRecoveryNoContentCode int = 204

/*
PostChallRecoveryNoContent Recovery account with success

swagger:response postChallRecoveryNoContent
*/
type PostChallRecoveryNoContent struct {
}

// NewPostChallRecoveryNoContent creates PostChallRecoveryNoContent with default headers values
func NewPostChallRecoveryNoContent() *PostChallRecoveryNoContent {

	return &PostChallRecoveryNoContent{}
}

// WriteResponse to the client
func (o *PostChallRecoveryNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// PostChallRecoveryBadRequestCode is the HTTP code returned for type PostChallRecoveryBadRequest
const PostChallRecoveryBadRequestCode int = 400

/*
PostChallRecoveryBadRequest requested body reaches malformed

swagger:response postChallRecoveryBadRequest
*/
type PostChallRecoveryBadRequest struct {
}

// NewPostChallRecoveryBadRequest creates PostChallRecoveryBadRequest with default headers values
func NewPostChallRecoveryBadRequest() *PostChallRecoveryBadRequest {

	return &PostChallRecoveryBadRequest{}
}

// WriteResponse to the client
func (o *PostChallRecoveryBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostChallRecoveryForbiddenCode is the HTTP code returned for type PostChallRecoveryForbidden
const PostChallRecoveryForbiddenCode int = 403

/*
PostChallRecoveryForbidden incorrect validation number

swagger:response postChallRecoveryForbidden
*/
type PostChallRecoveryForbidden struct {
}

// NewPostChallRecoveryForbidden creates PostChallRecoveryForbidden with default headers values
func NewPostChallRecoveryForbidden() *PostChallRecoveryForbidden {

	return &PostChallRecoveryForbidden{}
}

// WriteResponse to the client
func (o *PostChallRecoveryForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// PostChallRecoveryGoneCode is the HTTP code returned for type PostChallRecoveryGone
const PostChallRecoveryGoneCode int = 410

/*
PostChallRecoveryGone Recovery ticket has been expired

swagger:response postChallRecoveryGone
*/
type PostChallRecoveryGone struct {
}

// NewPostChallRecoveryGone creates PostChallRecoveryGone with default headers values
func NewPostChallRecoveryGone() *PostChallRecoveryGone {

	return &PostChallRecoveryGone{}
}

// WriteResponse to the client
func (o *PostChallRecoveryGone) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(410)
}

// PostChallRecoveryInternalServerErrorCode is the HTTP code returned for type PostChallRecoveryInternalServerError
const PostChallRecoveryInternalServerErrorCode int = 500

/*
PostChallRecoveryInternalServerError Occurs unexpected internal error

swagger:response postChallRecoveryInternalServerError
*/
type PostChallRecoveryInternalServerError struct {
}

// NewPostChallRecoveryInternalServerError creates PostChallRecoveryInternalServerError with default headers values
func NewPostChallRecoveryInternalServerError() *PostChallRecoveryInternalServerError {

	return &PostChallRecoveryInternalServerError{}
}

// WriteResponse to the client
func (o *PostChallRecoveryInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
