// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostRecoveryHandlerFunc turns a function with the right signature into a post recovery handler
type PostRecoveryHandlerFunc func(PostRecoveryParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostRecoveryHandlerFunc) Handle(params PostRecoveryParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostRecoveryHandler interface for that can handle valid post recovery params
type PostRecoveryHandler interface {
	Handle(PostRecoveryParams, interface{}) middleware.Responder
}

// NewPostRecovery creates a new http.Handler for the post recovery operation
func NewPostRecovery(ctx *middleware.Context, handler PostRecoveryHandler) *PostRecovery {
	return &PostRecovery{Context: ctx, Handler: handler}
}

/*
	PostRecovery swagger:route POST /recovery postRecovery

Open recovery account process
*/
type PostRecovery struct {
	Context *middleware.Context
	Handler PostRecoveryHandler
}

func (o *PostRecovery) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostRecoveryParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostRecoveryCreatedBody post recovery created body
//
// swagger:model PostRecoveryCreatedBody
type PostRecoveryCreatedBody struct {

	// The ticket recovery ID
	ID string `json:"id,omitempty"`
}

// Validate validates this post recovery created body
func (o *PostRecoveryCreatedBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post recovery created body based on context it is used
func (o *PostRecoveryCreatedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostRecoveryCreatedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostRecoveryCreatedBody) UnmarshalBinary(b []byte) error {
	var res PostRecoveryCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
