# DO NOT USE THIS FILE IN PRODUCTION!
# THIS FILE WAS CREATED FOR ONLY TESTS PURPOSE

version: '3'
services:
  database:
    image: database:latest
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=identities
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=someAwesomePassword

  api-identities:
    image: identities:latest
    network_mode: host
    depends_on:
      - database
    environment:
      - DB_NAME=identities
      - DB_USER=postgres
      - DB_HOST=localhost
      - DB_PASSWORD=someAwesomePassword
      - JWT_KEY=someEncryptedKey
      - API_KEY=SomeApiKey
      - CLOUDINARY_CLOUD_NAME=ddp1zqajp
      - CLOUDINARY_API_KEY=551242643183929
      - CLOUDINARY_API_SECRET=DORrwt4TO0-Ce7r-9yTZ0w_Hp_o
      - CLOUDINARY_UPLOAD_FOLDER=dakasa