# DO NOT USE THIS FILE IN PRODUCTION!
# THIS FILE WAS CREATED FOR ONLY TESTS PURPOSE

version: '3'
services:
  database:
    image: id-database:latest
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=identities
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=someAwesomePassword

  api-identities:
    image: identities:0.1.0
    network_mode: host
    depends_on:
      - database
    environment:
      - DB_NAME=identities
      - DB_USER=postgres
      - DB_HOST=localhost
      - DB_PASSWORD=someAwesomePassword
      - JWT_KEY=someEncryptedKey
      - API_KEY=SomeApiKey
      - CLOUDINARY_CLOUD_NAME=<YOUR CLOUD NAME HERE>
      - CLOUDINARY_API_KEY=<YOUR API KEY HERE>
      - CLOUDINARY_API_SECRET=<YOUR API SECRET HERE>
      - CLOUDINARY_UPLOAD_FOLDER=dakasa
      - TEST_IGNORE_EMAIL=true