name: Deploy api-identities PRD

on:
  pull_request: 
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'
          cache: false

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Running Unit Tests
        run: task test:unit

      - name: Validate API Docs
        run: task validate-docs

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'
          cache: false
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53

  deploy:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'
          cache: false

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Building images
        run: task build-images

      - name: Running Functional Tests
        run: task test:functional
        env:
          DB_NAME: identities
          DB_USER: postgres
          DB_HOST: localhost
          DB_PASSWORD: someAwesomePassword


      # TO DO: The real deploy goes here

